# Generated by Django 4.2.4 on 2023-08-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member_acc',
            name='Date',
            field=models.DateField(null=True),
        ),
    ]
