# Generated by Django 4.2.4 on 2023-08-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sca', '0002_member_acc_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Currencyone', models.CharField(max_length=255)),
                ('Currencytwo', models.CharField(max_length=255)),
                ('Valueone', models.CharField(max_length=255)),
                ('Valuetwo', models.CharField(max_length=255)),
            ],
        ),
    ]
